### PR TITLE
Re-write for jasmine2's event-driven style, in a way that doesn't rely on jasmine internals

### PR DESCRIPTION
**Pull request by alextreppass**
Also works with [jasmine#575](/pivotal/jasmine/pull/575) for totalCount and passedCount, which are currently missing.

See #7 for context

### CODE REVIEW

**Comment by alextreppass** [comment]
I realise this is a pretty sweeping change. Shoot if you have any questions!

**Comment by detro** [comment]
Looking at it.

**Comment by detro** [comment]
Question: do you think this need an update to the README section on how to use it?
Even, an extra example to add to the examples directory?

I say this as I think the `jasmine-2.0` branch will have, at some point, merge with `master` and the 2 versions need to live side-by-side.
Both Jasmine 1.x and 2.x are used: I don't plan to drop the version that works with 1.0 just yet.

Anyhow, the code look good.

**Comment by alextreppass** [comment]
Thanks.

Usage should be the same as the first one, i.e.:
- jasmine.getEnv().addReporter(new jasmine.JSReporter())
- window.jasmine.getJSReport()
- window.jasmine.getJSReportAsString()

It should produce a report compatible with things that use the 1.x reporter.

If we want them side-by-side, should we namespace this one as jasmine.jsReporter2?

**Comment by detro** [comment]
OK for usage.

I think you just had a great idea!
Namespacing it so that both can live within the same file: a very good plan.

**Comment by alextreppass** [comment]
I'll rename the file too and rebase this PR tomorrow

**Comment by alextreppass** [comment]
Oh unless you want both in the same JS file? In which case I can update my
PR to include the original!

**Comment by detro** [comment]
I think both in the same file would be cool. Maybe with some notes in the
Readme on how to use it in v1 and v2.

What do you think?

**Comment by alextreppass** [comment]
Sounds good

**Comment by alextreppass** [comment]
Should be good to go!

**Comment by detro** [comment]
Thanks a lot for your hard work Alex!!!

**Comment by detro** [comment]
Your patch depends on UnderscoreJS???
Why haven't you mentioned that?
Or noted that anywhere???

**Comment by alextreppass** [comment]
Oh sorry - I could have sworn Jasmine itself depended on underscore.

I can rewrite to not use underscore if that helps?

**Comment by alextreppass** [comment]
Here you go - #12 - pretty quick & dirty, hope that'll suffice

**Pull request merged**
