### PR TITLE
Added support for jasmine 2.0.0 while maintaining similar interface

### PR DESCRIPTION
**Pull request by sclevine**
As far as I can tell, Jasmine 2 doesn't expose the number of passed expectations per spec, so the passedCount/failedCount/totalCount are all 1 or 0. It also doesn't expose the nesting in the callback functions, so we parse `jasmine.getEnv().topSuite()` instead.

But, this will allow most things expecting JSReporter output to work with jasmine 2. It may make more sense to leave this on a branch.

### CODE REVIEW

**Comment by alextreppass** [comment]
I've had a play with this version, and due to jasmine not exposing enough information, it reports `"durationSec": null` for each suite/spec, and information on the number of specs total / passed / failed are no-longer available so we get binary passedCount/failedCount/totalCount which is less than ideal.

I wonder if we need to ask the jasmine guys to make their specs easier to instrument / report on. It seems that sort of information is no-longer exposed.

**Comment by sclevine** [comment]
Hi @alextreppass,

I don't seem to be getting the same errors. I'm a maintainer of [dc.js](https://github.com/dc-js/dc.js) and wrote this to get OpenSauce working with our Jasmine 2 specs. Here's what some of the jsreporter output for our suite looks like: https://saucelabs.com/tests/ffb768eb7ba74d14a6f9d0b40985a549 and https://saucelabs.com/tests/8ad4480dfb434d90ac10d4b31abf84d8 (under metadata).

(Unfortunately, Sauce Labs seems to ignore this input when it gets too large. If I combine these suites together (with no extra tests) the reporter outputs correct looking JSON locally, but Sauce seems to parse it as `null`: https://saucelabs.com/tests/48c9d3f6f7414f12b415ab1477cb6cd9)

This could still be some issue with the above pull request. Let me know if you figure anything out.

**Comment by sclevine** [comment]
Sauce Labs just got back to me, and they do believe it's a length issue with that field. So I don't believe there are any other issues with this pull request.

(@alextreppass: It should be compatible with Sauce Labs, for sufficiently small suites. They suggested I strip out all of the passing specs until they have a fix.)

**Comment by detro** [comment]
Let's do like this.
I'll create a Jasmine-2.0 branch and this can go against that instead of master, so we don't break compatibility with the previous Jasmine.

**Comment by detro** [comment]
OK.
I have created branch `jasmine-2.0`. Feel free to change this to be a PR against that.
I'm not sure you can re-target it, so maybe a new PR is required.

Close this one once we have that.

**Comment by sclevine** [comment]
Re-targeting a branch is currently [not possible](https://github.com/isaacs/github/issues/18). Check out #8. Closing this PR.

**Pull request closed without merging**
